package com.example.battleship.view;

import com.example.battleship.view.assets.ShotMark3D;
import com.example.battleship.view.assets.Water3D;

import com.example.battleship.view.ships.Ship3D;
import javafx.scene.AmbientLight;
import javafx.scene.Group;
import javafx.scene.Node;
import javafx.scene.PerspectiveCamera;
import javafx.scene.PointLight;
import javafx.scene.SubScene;
import javafx.scene.SceneAntialiasing;
import javafx.scene.paint.Color;
import javafx.scene.transform.Rotate;

/**
 * 3D view of the 10x10 board. Wraps its own {@link SubScene} with a
 * perspective camera and lights, so it can be embedded inside any 2D
 * layout of the rest of the interface (for example inside a
 * {@code BorderPane} or {@code StackPane} of the main JavaFX/FXML
 * application).
 * <p>
 * Note: JavaFX does not allow mixing 2D and 3D nodes in the same scene
 * graph; that is why everything the player sees (water, ships and shot
 * marks) lives inside this {@code SubScene}.
 * </p>
 */
public class BoardView3D extends SubScene {

    /** Number of rows on the board. */
    public static final int ROWS = 10;
    /** Number of columns on the board. */
    public static final int COLUMNS = 10;

    private final Group root3D;

    /**
     * Builds a single 10x10 board, its own fixed camera, lighting, and
     * water grid, ready to have ships and shot marks added to it.
     *
     * @param width  initial width of the embedded {@code SubScene}
     * @param height initial height of the embedded {@code SubScene}
     */
    public BoardView3D(double width, double height) {
        super(new Group(), width, height, true, SceneAntialiasing.BALANCED);
        this.root3D = (Group) getRoot();

        buildWaterGrid();
        setupCamera();
        setupLights();
        setFill(Color.rgb(10, 15, 25));
    }

    /** Fills {@link #root3D} with one {@link Water3D} tile per cell of the {@value #ROWS}x{@value #COLUMNS} grid. */
    private void buildWaterGrid() {
        for (int row = 0; row < ROWS; row++) {
            for (int column = 0; column < COLUMNS; column++) {
                root3D.getChildren().add(new Water3D(row, column));
            }
        }
    }

    /** Builds and installs a fixed, tilted-down camera framing the whole board -- see the rig comments below for why it's built this way. */
    private void setupCamera() {
        PerspectiveCamera camera = new PerspectiveCamera(true);
        camera.setNearClip(0.1);
        camera.setFarClip(3000);
        camera.setFieldOfView(45);

        double centerX = (COLUMNS - 1) * Config3D.CELL_SIZE / 2.0;
        double centerZ = (ROWS - 1) * Config3D.CELL_SIZE / 2.0;

        // Camera rig: a parent Group holds the tilt rotation and sits at
        // the point we want to look at (the board's center); the camera
        // is its child, offset only along Z. Because the camera has no
        // rotation of its own, it always ends up looking straight back
        // at its parent's local origin, no matter how the parent group
        // is rotated -- this avoids having to hand-compute a translateY
        // / translateZ that matches the tilt angle (which is what broke
        // the previous version and pointed the camera past the board).
        Group cameraRig = new Group();
        cameraRig.getTransforms().add(new Rotate(-35, Rotate.X_AXIS));
        cameraRig.setTranslateX(centerX);
        cameraRig.setTranslateY(-20); // aim slightly above the water plane, where the ships sit
        cameraRig.setTranslateZ(centerZ);

        camera.setTranslateZ(-600); // distance from the target, along the rig's tilted axis
        cameraRig.getChildren().add(camera);
        root3D.getChildren().add(cameraRig);

        setCamera(camera);
    }

    /** Adds a soft ambient fill light plus one point light, so the board's shapes read with visible shading instead of flat silhouettes. */
    private void setupLights() {
        AmbientLight ambientLight = new AmbientLight(Color.rgb(150, 150, 160));
        PointLight pointLight = new PointLight(Color.WHITE);
        pointLight.setTranslateX((COLUMNS - 1) * Config3D.CELL_SIZE / 2.0);
        pointLight.setTranslateZ(-250);
        pointLight.setTranslateY(-400);
        root3D.getChildren().addAll(ambientLight, pointLight);
    }

    /** Adds an already built ship (position and orientation are set at creation time). */
    public void addShip(Ship3D ship) {
        root3D.getChildren().add(ship);
    }

    /** Adds any shot mark (water miss, hit, etc.) generated by {@link ShotMark3D}. */
    public void addMark(Node mark) {
        root3D.getChildren().add(mark);
    }
}